CREATE TABLE ANUNCIO(
	IDANUNCIO SERIAL PRIMARY KEY,
	TITULO VARCHAR(150),
	DESCRICAO VARCHAR(500),
	DATA_INICIAL DATE,
	DATA_FINAL DATE,
	CATEGORIA VARCHAR(25),
	TELEFONE CHAR(12),
	EMAIL VARCHAR(255),
	SRC VARCHAR(150)
);