DROP TABLE ANUNCIO;

CREATE TABLE ANUNCIO(
	IDANUNCIO SERIAL PRIMARY KEY,
	TITULO VARCHAR(150),
	DESCRICAO VARCHAR(250),
	DATA_INICIAL DATE,
	DATA_FINAL DATE,
	CATEGORIA VARCHAR(25),
	TELEFONE INT,
	EMAIL VARCHAR(150),
	SRC VARCHAR(150)
);

SELECT * FROM ANUNCIO;